/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_11 (number 1), GPIO_11 */
#define BOARD_LED_TEST_PERIPHERAL                                          GPIO1   /*!< Device name: GPIO1 */
#define BOARD_LED_TEST_SIGNAL                                         gpiomux_io   /*!< GPIO1 signal: gpiomux_io */
#define BOARD_LED_TEST_CHANNEL                                               11U   /*!< GPIO1 gpiomux_io channel: 11 */

/* GPIO_AD_04 (number 56), LPSPI1_SDO/J57[8]/U27[5] */
#define BOARD_D5_57_08_PERIPHERAL                                          GPIO1   /*!< Device name: GPIO1 */
#define BOARD_D5_57_08_SIGNAL                                         gpiomux_io   /*!< GPIO1 signal: gpiomux_io */
#define BOARD_D5_57_08_CHANNEL                                               18U   /*!< GPIO1 gpiomux_io channel: 18 */

/* GPIO_AD_05 (number 55), LPSPI1_PCS0/INT1_COMBO/J56[6]/J57[6]/U26[11]/U27[1] */
#define BOARD_D6_57_06_PERIPHERAL                                          GPIO1   /*!< Device name: GPIO1 */
#define BOARD_D6_57_06_SIGNAL                                         gpiomux_io   /*!< GPIO1 signal: gpiomux_io */
#define BOARD_D6_57_06_CHANNEL                                               19U   /*!< GPIO1 gpiomux_io channel: 19 */

/* GPIO_01 (number 12), I2C1_SDA/U10[18]/J57[18]/U26[6] */
#define BOARD_D0_57_18_PERIPHERAL                                          GPIO1   /*!< Device name: GPIO1 */
#define BOARD_D0_57_18_SIGNAL                                         gpiomux_io   /*!< GPIO1 signal: gpiomux_io */
#define BOARD_D0_57_18_CHANNEL                                                1U   /*!< GPIO1 gpiomux_io channel: 01 */

/* GPIO_02 (number 11), I2C1_SCL/U10[17]/J57[20]/U26[4] */
#define BOARD_D1_57_20_PERIPHERAL                                          GPIO1   /*!< Device name: GPIO1 */
#define BOARD_D1_57_20_SIGNAL                                         gpiomux_io   /*!< GPIO1 signal: gpiomux_io */
#define BOARD_D1_57_20_CHANNEL                                                2U   /*!< GPIO1 gpiomux_io channel: 02 */

/* GPIO_AD_03 (number 57), LPSPI1_SDI/J57[10]/U27[2] */
#define BOARD_D4_57_10_PERIPHERAL                                          GPIO1   /*!< Device name: GPIO1 */
#define BOARD_D4_57_10_SIGNAL                                         gpiomux_io   /*!< GPIO1 signal: gpiomux_io */
#define BOARD_D4_57_10_CHANNEL                                               17U   /*!< GPIO1 gpiomux_io channel: 17 */

/* GPIO_AD_02 (number 58), ADC12_2/J26[12]/J56[16] */
#define BOARD_D3_56_16_PERIPHERAL                                          GPIO1   /*!< Device name: GPIO1 */
#define BOARD_D3_56_16_SIGNAL                                         gpiomux_io   /*!< GPIO1 signal: gpiomux_io */
#define BOARD_D3_56_16_CHANNEL                                               16U   /*!< GPIO1 gpiomux_io channel: 16 */

/* GPIO_AD_01 (number 59), ADC12_1/J26[10]/J56[14] */
#define BOARD_D2_56_14_PERIPHERAL                                          GPIO1   /*!< Device name: GPIO1 */
#define BOARD_D2_56_14_SIGNAL                                         gpiomux_io   /*!< GPIO1 signal: gpiomux_io */
#define BOARD_D2_56_14_CHANNEL                                               15U   /*!< GPIO1 gpiomux_io channel: 15 */

/* GPIO_AD_06 (number 52), LPSPI1_SCK/INT2_COMBO/J56[8]/J57[12]/U26[9]/U27[6] */
#define BOARD_D7_57_12_PERIPHERAL                                          GPIO1   /*!< Device name: GPIO1 */
#define BOARD_D7_57_12_SIGNAL                                         gpiomux_io   /*!< GPIO1 signal: gpiomux_io */
#define BOARD_D7_57_12_CHANNEL                                               20U   /*!< GPIO1 gpiomux_io channel: 20 */

/* GPIO_AD_07 (number 51), ADC12_3/J26[2] */
#define BOARD_CS_26_2_PERIPHERAL                                           GPIO1   /*!< Device name: GPIO1 */
#define BOARD_CS_26_2_SIGNAL                                          gpiomux_io   /*!< GPIO1 signal: gpiomux_io */
#define BOARD_CS_26_2_CHANNEL                                                21U   /*!< GPIO1 gpiomux_io channel: 21 */

/* GPIO_AD_09 (number 48), ADC12_4/JTAG_TDO/J55[6]/J26[4] */
#define BOARD_WR_26_04_PERIPHERAL                                          GPIO1   /*!< Device name: GPIO1 */
#define BOARD_WR_26_04_SIGNAL                                         gpiomux_io   /*!< GPIO1 signal: gpiomux_io */
#define BOARD_WR_26_04_CHANNEL                                               23U   /*!< GPIO1 gpiomux_io channel: 23 */

/* GPIO_AD_14 (number 43), ADC12_6/J26[8] */
#define BOARD_CD_26_08_PERIPHERAL                                          GPIO1   /*!< Device name: GPIO1 */
#define BOARD_CD_26_08_SIGNAL                                         gpiomux_io   /*!< GPIO1 signal: gpiomux_io */
#define BOARD_CD_26_08_CHANNEL                                               28U   /*!< GPIO1 gpiomux_io channel: 28 */

/* GPIO_10 (number 2), LPUART1_TXD/J56[4] */
#define BOARD_DATA_56_04_PERIPHERAL                                        GPIO1   /*!< Device name: GPIO1 */
#define BOARD_DATA_56_04_SIGNAL                                       gpiomux_io   /*!< GPIO1 signal: gpiomux_io */
#define BOARD_DATA_56_04_CHANNEL                                             10U   /*!< GPIO1 gpiomux_io channel: 10 */

/* GPIO_SD_02 (number 74), GPIO2_02 */
#define BOARD_GATE_57_02_GPIO                                              GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_GATE_57_02_PORT                                              GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_GATE_57_02_PIN                                                  2U   /*!< GPIO2 pin index: 2 */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
