/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v6.0
processor: MIMXRT1011xxxxx
package_id: MIMXRT1011DAE5A
mcu_data: ksdk2_0
processor_version: 6.0.0
board: MIMXRT1010-EVK
pin_labels:
- {pin_num: '3', pin_signal: GPIO_09, label: GPIO1_09, identifier: UART1_RXD;GPIO1_09;SiLab_RX;GATE_56_02}
- {pin_num: '2', pin_signal: GPIO_10, label: 'LPUART1_TXD/J56[4]', identifier: UART1_TXD;RST_56_04;DATA_56_04}
- {pin_num: '65', pin_signal: GPIO_SD_10, label: 'FlexSPI_CLK_A/U13[6]', identifier: FlexSPI_CLK;GPIO2_10}
- {pin_num: '66', pin_signal: GPIO_SD_09, label: 'FlexSPI_D0_A/U13[5]', identifier: FlexSPI_D0_A;GPIO2_09}
- {pin_num: '68', pin_signal: GPIO_SD_07, label: 'FlexSPI_D1_A/U13[2]', identifier: FlexSPI_D1_A;GPIO2_07}
- {pin_num: '67', pin_signal: GPIO_SD_08, label: 'FlexSPI_D2_A/U13[3]', identifier: FlexSPI_D2_A;GPIO2_08}
- {pin_num: '64', pin_signal: GPIO_SD_11, label: 'FlexSPI_D3_A/U13[7]', identifier: FlexSPI_D3_A;GPIO2_11}
- {pin_num: '69', pin_signal: GPIO_SD_06, label: 'FlexSPI_SS0/U13[1]', identifier: FlexSPI_SS0;GPIO2_06}
- {pin_num: '1', pin_signal: GPIO_11, label: GPIO_11, identifier: GPIO_11;LED_TEST}
- {pin_num: '11', pin_signal: GPIO_02, label: 'I2C1_SCL/U10[17]/J57[20]/U26[4]', identifier: I2C1_SCL;LED_57_20;D1_57_20}
- {pin_num: '12', pin_signal: GPIO_01, label: 'I2C1_SDA/U10[18]/J57[18]/U26[6]', identifier: I2C1_SDA;LED_57_18;D0;D0_57_18}
- {pin_num: '10', pin_signal: GPIO_03, label: 'SAI1_RXD0/U10[16]', identifier: SAI1_RXD0;GPIO1_03}
- {pin_num: '9', pin_signal: GPIO_04, label: 'SAI1_TXD0/U10[14]', identifier: SAI1_TXD0;GPIO1_04}
- {pin_num: '8', pin_signal: GPIO_05, label: SAI1_TXD1, identifier: SAI1_TXD1;GPIO1_05}
- {pin_num: '6', pin_signal: GPIO_06, label: 'SAI1_TX_BCLK/U10[12]', identifier: SAI1_TX_BCLK;GPIO_06;GPIO1_06}
- {pin_num: '5', pin_signal: GPIO_07, label: 'SAI1_TX_SYNC/U10[13]', identifier: SAI1_TX_SYNC;GPIO1_07}
- {pin_num: '4', pin_signal: GPIO_08, label: 'SAI1_MCLK/U10[11]', identifier: SAI1_MCLK;GPIO1_08}
- {pin_num: '59', pin_signal: GPIO_AD_01, label: 'ADC12_1/J26[10]/J56[14]', identifier: ADC12_1;LED_56_14;D2_56_14}
- {pin_num: '58', pin_signal: GPIO_AD_02, label: 'ADC12_2/J26[12]/J56[16]', identifier: ADC12_2;LED_57_16;LED_56_16;D3_56_16}
- {pin_num: '57', pin_signal: GPIO_AD_03, label: 'LPSPI1_SDI/J57[10]/U27[2]', identifier: LPSPI1_SDI;LED_57_10;D4_57_10}
- {pin_num: '56', pin_signal: GPIO_AD_04, label: 'LPSPI1_SDO/J57[8]/U27[5]', identifier: LPSPI1_SDO;LED_57_08;D5_57_08}
- {pin_num: '55', pin_signal: GPIO_AD_05, label: 'LPSPI1_PCS0/INT1_COMBO/J56[6]/J57[6]/U26[11]/U27[1]', identifier: LPSPI1_PCS0;LED_57_06;D6_57_06}
- {pin_num: '52', pin_signal: GPIO_AD_06, label: 'LPSPI1_SCK/INT2_COMBO/J56[8]/J57[12]/U26[9]/U27[6]', identifier: LPSPI1_SCK;LED_57_20;LED_57_12;D7_57_12}
- {pin_num: '51', pin_signal: GPIO_AD_07, label: 'ADC12_3/J26[2]', identifier: ADC12_3;CS_26_2}
- {pin_num: '13', pin_signal: GPIO_00, label: 'AUD_INT/U10[15]', identifier: AUD_INT;GPIO1_00}
- {pin_num: '80', pin_signal: GPIO_12, label: GPIO1_12, identifier: USB_OTG1_OC;GPIO1_12}
- {pin_num: '79', pin_signal: GPIO_13, label: GPIO1_13, identifier: USB_OTG1_ID;GPIO1_13}
- {pin_num: '60', pin_signal: GPIO_AD_00, label: USB_OTG1_PWR, identifier: USB_OTG1_PWR;GPIO1_14}
- {pin_num: '49', pin_signal: GPIO_AD_08, label: 'JTAG_TRSTB/J55[10]', identifier: JTAG_TRSTB;CD;GPIO1_22}
- {pin_num: '48', pin_signal: GPIO_AD_09, label: 'ADC12_4/JTAG_TDO/J55[6]/J26[4]', identifier: ADC12_4;WR_26_04}
- {pin_num: '47', pin_signal: GPIO_AD_10, label: 'ADC12_5/JTAG_TDI/J55[8]/J26[6]', identifier: ADC12_5;RD_26_06;GATE_26_06}
- {pin_num: '45', pin_signal: GPIO_AD_12, label: 'JTAG_TCK/J55[4]', identifier: JTAG_TCK;GPIO1_26}
- {pin_num: '44', pin_signal: GPIO_AD_13, label: 'JTAG_TMS/J55[2]', identifier: JTAG_TMS;GPIO1_27}
- {pin_num: '43', pin_signal: GPIO_AD_14, label: 'ADC12_6/J26[8]', identifier: ADC12_6;CD_26_08}
- {pin_num: '76', pin_signal: GPIO_SD_00, label: 'GPIO_SD_00/BT_CFG[2]', identifier: GPIO_SD_00;GPIO2_00}
- {pin_num: '75', pin_signal: GPIO_SD_01, label: 'GPIO_SD_01/BT_CFG[1]/TP31', identifier: GPIO_SD_01;GPIO2_01}
- {pin_num: '74', pin_signal: GPIO_SD_02, label: GPIO2_02, identifier: GPIO_SD_02;GPIO2_02;GATE_57_02}
- {pin_num: '73', pin_signal: GPIO_SD_03, label: 'GPIO_SD_03/BOOT_MODE[1]', identifier: GPIO_SD_03;GPIO2_03}
- {pin_num: '72', pin_signal: GPIO_SD_04, label: 'GPIO_SD_04/BOOT_MODE[0]', identifier: GPIO_SD_04;GPIO2_04}
- {pin_num: '61', pin_signal: GPIO_SD_13, label: 'GPIO_SD_13/BT_CFG[3]', identifier: GPIO_SD_13;GPIO2_13}
- {pin_num: '62', pin_signal: GPIO_SD_12, label: TP33, identifier: GPIO2_12}
power_domains: {NVCC_GPIO: '3.3'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_InitPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', prefix: BOARD_, coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '1', peripheral: GPIO1, signal: 'gpiomux_io, 11', pin_signal: GPIO_11, identifier: LED_TEST, direction: OUTPUT}
  - {pin_num: '56', peripheral: GPIO1, signal: 'gpiomux_io, 18', pin_signal: GPIO_AD_04, identifier: D5_57_08, direction: OUTPUT}
  - {pin_num: '55', peripheral: GPIO1, signal: 'gpiomux_io, 19', pin_signal: GPIO_AD_05, identifier: D6_57_06, direction: OUTPUT}
  - {pin_num: '12', peripheral: GPIO1, signal: 'gpiomux_io, 01', pin_signal: GPIO_01, identifier: D0_57_18, direction: OUTPUT}
  - {pin_num: '11', peripheral: GPIO1, signal: 'gpiomux_io, 02', pin_signal: GPIO_02, identifier: D1_57_20, direction: OUTPUT}
  - {pin_num: '57', peripheral: GPIO1, signal: 'gpiomux_io, 17', pin_signal: GPIO_AD_03, identifier: D4_57_10, direction: OUTPUT}
  - {pin_num: '58', peripheral: GPIO1, signal: 'gpiomux_io, 16', pin_signal: GPIO_AD_02, identifier: D3_56_16, direction: OUTPUT}
  - {pin_num: '59', peripheral: GPIO1, signal: 'gpiomux_io, 15', pin_signal: GPIO_AD_01, identifier: D2_56_14, direction: OUTPUT}
  - {pin_num: '52', peripheral: GPIO1, signal: 'gpiomux_io, 20', pin_signal: GPIO_AD_06, identifier: D7_57_12, direction: OUTPUT}
  - {pin_num: '51', peripheral: GPIO1, signal: 'gpiomux_io, 21', pin_signal: GPIO_AD_07, identifier: CS_26_2, direction: OUTPUT}
  - {pin_num: '48', peripheral: GPIO1, signal: 'gpiomux_io, 23', pin_signal: GPIO_AD_09, identifier: WR_26_04, direction: OUTPUT}
  - {pin_num: '43', peripheral: GPIO1, signal: 'gpiomux_io, 28', pin_signal: GPIO_AD_14, identifier: CD_26_08, direction: OUTPUT}
  - {pin_num: '2', peripheral: GPIO1, signal: 'gpiomux_io, 10', pin_signal: GPIO_10, identifier: DATA_56_04, direction: INPUT, pull_up_down_config: Pull_Up_100K_Ohm}
  - {pin_num: '74', peripheral: GPIO2, signal: 'gpio_io, 02', pin_signal: GPIO_SD_02, identifier: GATE_57_02, direction: INPUT, pull_up_down_config: Pull_Up_100K_Ohm}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* iomuxc clock (iomuxc_clk_enable): 0x03U */

  /* GPIO configuration of D0_57_18 on GPIO_01 (pin 12) */
  gpio_pin_config_t D0_57_18_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_01 (pin 12) */
  GPIO_PinInit(GPIO1, 1U, &D0_57_18_config);

  /* GPIO configuration of D1_57_20 on GPIO_02 (pin 11) */
  gpio_pin_config_t D1_57_20_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_02 (pin 11) */
  GPIO_PinInit(GPIO1, 2U, &D1_57_20_config);

  /* GPIO configuration of DATA_56_04 on GPIO_10 (pin 2) */
  gpio_pin_config_t DATA_56_04_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_10 (pin 2) */
  GPIO_PinInit(GPIO1, 10U, &DATA_56_04_config);

  /* GPIO configuration of LED_TEST on GPIO_11 (pin 1) */
  gpio_pin_config_t LED_TEST_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_11 (pin 1) */
  GPIO_PinInit(GPIO1, 11U, &LED_TEST_config);

  /* GPIO configuration of D2_56_14 on GPIO_AD_01 (pin 59) */
  gpio_pin_config_t D2_56_14_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_01 (pin 59) */
  GPIO_PinInit(GPIO1, 15U, &D2_56_14_config);

  /* GPIO configuration of D3_56_16 on GPIO_AD_02 (pin 58) */
  gpio_pin_config_t D3_56_16_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_02 (pin 58) */
  GPIO_PinInit(GPIO1, 16U, &D3_56_16_config);

  /* GPIO configuration of D4_57_10 on GPIO_AD_03 (pin 57) */
  gpio_pin_config_t D4_57_10_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_03 (pin 57) */
  GPIO_PinInit(GPIO1, 17U, &D4_57_10_config);

  /* GPIO configuration of D5_57_08 on GPIO_AD_04 (pin 56) */
  gpio_pin_config_t D5_57_08_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_04 (pin 56) */
  GPIO_PinInit(GPIO1, 18U, &D5_57_08_config);

  /* GPIO configuration of D6_57_06 on GPIO_AD_05 (pin 55) */
  gpio_pin_config_t D6_57_06_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_05 (pin 55) */
  GPIO_PinInit(GPIO1, 19U, &D6_57_06_config);

  /* GPIO configuration of D7_57_12 on GPIO_AD_06 (pin 52) */
  gpio_pin_config_t D7_57_12_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_06 (pin 52) */
  GPIO_PinInit(GPIO1, 20U, &D7_57_12_config);

  /* GPIO configuration of CS_26_2 on GPIO_AD_07 (pin 51) */
  gpio_pin_config_t CS_26_2_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_07 (pin 51) */
  GPIO_PinInit(GPIO1, 21U, &CS_26_2_config);

  /* GPIO configuration of WR_26_04 on GPIO_AD_09 (pin 48) */
  gpio_pin_config_t WR_26_04_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_09 (pin 48) */
  GPIO_PinInit(GPIO1, 23U, &WR_26_04_config);

  /* GPIO configuration of CD_26_08 on GPIO_AD_14 (pin 43) */
  gpio_pin_config_t CD_26_08_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_14 (pin 43) */
  GPIO_PinInit(GPIO1, 28U, &CD_26_08_config);

  /* GPIO configuration of GATE_57_02 on GPIO_SD_02 (pin 74) */
  gpio_pin_config_t GATE_57_02_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_SD_02 (pin 74) */
  GPIO_PinInit(GPIO2, 2U, &GATE_57_02_config);

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_01_GPIOMUX_IO01,            /* GPIO_01 is configured as GPIOMUX_IO01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_02_GPIOMUX_IO02,            /* GPIO_02 is configured as GPIOMUX_IO02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_10_GPIOMUX_IO10,            /* GPIO_10 is configured as GPIOMUX_IO10 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_11_GPIOMUX_IO11,            /* GPIO_11 is configured as GPIOMUX_IO11 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_01_GPIOMUX_IO15,         /* GPIO_AD_01 is configured as GPIOMUX_IO15 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_02_GPIOMUX_IO16,         /* GPIO_AD_02 is configured as GPIOMUX_IO16 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_03_GPIOMUX_IO17,         /* GPIO_AD_03 is configured as GPIOMUX_IO17 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_04_GPIOMUX_IO18,         /* GPIO_AD_04 is configured as GPIOMUX_IO18 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_05_GPIOMUX_IO19,         /* GPIO_AD_05 is configured as GPIOMUX_IO19 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_06_GPIOMUX_IO20,         /* GPIO_AD_06 is configured as GPIOMUX_IO20 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_07_GPIOMUX_IO21,         /* GPIO_AD_07 is configured as GPIOMUX_IO21 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_09_GPIOMUX_IO23,         /* GPIO_AD_09 is configured as GPIOMUX_IO23 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_14_GPIOMUX_IO28,         /* GPIO_AD_14 is configured as GPIOMUX_IO28 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_02_GPIO2_IO02,           /* GPIO_SD_02 is configured as GPIO2_IO02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_GPR->GPR26 = ((IOMUXC_GPR->GPR26 &
    (~(IOMUXC_GPR_GPR26_GPIO_SEL_MASK)))      /* Mask bits to zero which are setting */
      | IOMUXC_GPR_GPR26_GPIO_SEL(0x00U)      /* Select GPIO1 or GPIO2: 0x00U */
    );
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_10_GPIOMUX_IO10,            /* GPIO_10 PAD functional properties : */
      0x90A0U);                               /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/4
                                                 Speed Field: fast(150MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Keeper
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_SD_02_GPIO2_IO02,           /* GPIO_SD_02 PAD functional properties : */
      0x90A0U);                               /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/4
                                                 Speed Field: fast(150MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Keeper
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Disabled */
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
